function(add_v2_test name source)
    add_executable(${name} ${CMAKE_CURRENT_LIST_DIR}/${source})
    target_link_libraries(${name} PRIVATE v2_core GTest::gtest_main GTest::gmock)
    target_include_directories(${name} PRIVATE ${CMAKE_SOURCE_DIR}/src)
    gtest_discover_tests(${name})
endfunction()

add_v2_test(test_ring_buffer core/test_ring_buffer.cpp)
add_v2_test(test_mailbox core/test_mpsc_queue.cpp)
add_v2_test(test_actor_registry core/test_actor_registry.cpp)
add_v2_test(test_timer core/test_timer.cpp)
add_v2_test(test_dispatcher core/test_dispatcher.cpp)
add_v2_test(test_actor core/test_actor.cpp)
add_v2_test(test_actor_context core/test_actor_context.cpp)
add_v2_test(test_scheduler core/test_scheduler.cpp)
add_v2_test(test_worker core/test_worker.cpp)
add_v2_test(test_actor_system core/test_actor_system.cpp)
